apiVersion: v1
kind: Service
metadata:
  name: example-etcdcluster
  labels:
    app: example-etcdcluster
spec:
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  clusterIP: None
  selector:
    app: example-etcdcluster
---

