apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.clusters.etcd.io
spec:
  group: clusters.etcd.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: integer
                  minimum: 1
                  maximum: 10
                registry:
                  type: string
                version:
                  type: string
            status:
              type: object
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: {}
  names:
    kind: EtcdCluster
    plural: etcdclusters
  scope: Namespaced
